In [1]:
import os
import requests
import json
import pandas as pd
import matplotlib.pyplot as plt
from pprint import pprint
import csv
import datetime
import numpy as np

## Pulled in csv from main youtube data script

In [2]:
read_csv = pd.read_csv("Music_Videos.csv")
df = pd.DataFrame(read_csv)
df["Release Date"] = df["Release Date"].apply(lambda x: f"{x}-2020")
df.head()

,Unnamed: 0,Name,View count,Like count,Dislike count,Comment count,Release Date
0,0,NBA YoungBoy - ALL IN,11422212,372373,11382,31300,07-25-2020
1,1,Billie Eilish - my future,19531868,2101425,46268,194242,07-30-2020
2,2,Mulatto - Muwop (Official Video) ft. Gucci Mane,3098639,135888,6412,6501,07-30-2020
3,3,"Beyoncé, Shatta Wale, Major Lazer – ALREADY (O...",6764911,555946,13093,40445,07-31-2020
4,4,YoungBoy Never Broke Again - One Shot feat. Li...,2535699,97774,2243,5389,07-30-2020

### Converting "Release Date" Column from string object to datetime object

In [3]:
df["Release Date"] = df["Release Date"].apply(lambda x: datetime.datetime.strptime(x,"%m-%d-%Y"))
df["Release Date"] = df["Release Date"].apply(lambda x: datetime.datetime.strftime(x, '%m-%d (%a)'))
df.head()

,Unnamed: 0,Name,View count,Like count,Dislike count,Comment count,Release Date
0,0,NBA YoungBoy - ALL IN,11422212,372373,11382,31300,07-25 (Sat)
1,1,Billie Eilish - my future,19531868,2101425,46268,194242,07-30 (Thu)
2,2,Mulatto - Muwop (Official Video) ft. Gucci Mane,3098639,135888,6412,6501,07-30 (Thu)
3,3,"Beyoncé, Shatta Wale, Major Lazer – ALREADY (O...",6764911,555946,13093,40445,07-31 (Fri)
4,4,YoungBoy Never Broke Again - One Shot feat. Li...,2535699,97774,2243,5389,07-30 (Thu)

### The following table shows:
### The top rated music video for each release date, sorted by viewcount in descending order.

In [4]:
release_date_max = df.groupby(df["Release Date"]).max().sort_values(by="View count", 
                                                        ascending = False)
release_date_max = release_date_max.drop(columns="Unnamed: 0")
top_four_list = ["07-23 (Thu)", "07-24 (Fri)", "07-17 (Fri)", "07-30 (Thu)"]
release_date_max.style.apply(lambda x: ['background: yellow' if x.name in top_four_list 
                                        else '' for i in x], axis=1)

### Here we see that the top 4 most viewed videos out of the 50 highest rated were all released on either Thursday or Friday.